<a href="https://colab.research.google.com/github/A01302935/David-Mireles-Samaniego/blob/main/Modulo_05_David_Mireles_Samaniego_A01302935.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# MODULO 5
# David Mireles Samaniego A01302935

In [ ]:
#The Basics & Array Creations

In [41]:
import numpy as np

In [47]:
a = ["0",1,"two","3",4] 

In [51]:
a[0]

0

In [52]:
a[1]

1

In [53]:
a[2]

2

In [ ]:
a[3]

In [55]:
a[4]

4

In [ ]:
a.dtype

In [63]:
a = np.array([0,1,2,3,4])

In [79]:
import numpy as np

u = np.array([1,0])
v = np.array([0,1])


In [84]:
z=u+v

In [ ]:
# TEST_05
# 

In [65]:
# QUESTION 1
# What is the result of the following operation: np.array([1,-1])*np.array([1,1])?
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [66]:
# QUESTION 2
# What is the result of the following operation: np.dot(np.array([1,-1]),np.array([1,1]))?
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [70]:
# Numpy 2D Arrays 
# QUESTION 1
# How many rows are in the following numpy array?

A = np.array([[1,2],[3,4],[5,6],[7,8]])

import numpy as np

arr = np.array([[1,2],[3,4],[5,6],[7,8]])

print(arr)

print(type(arr))

# ANS is 4

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
<class 'numpy.ndarray'>


In [83]:
# QUESTION 2
# Is it possible to perform the following operation?

# A = np.array([[1,2],[3,4],[5,6],[7,8]])

# B = np.array([[1,2,3],[4,5,6],[7,8,9]])

# np.dot(A,B)

# ANS = No for dimention

In [85]:
# What is the result of the following lines of code:

a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [86]:
# What is the result of the following lines of code:

a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [87]:
# What is the result of the following lines of code:

a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

In [88]:
# What is the correct code to perform matrix multiplication on the matrix A and B?
# ANS = np.dot(A,B)